#!/bin/bash
# A wrapper menu to omarchy-menu-keybindings to include more keybinds


menu() {
  local prompt="$1"
  local options="$2"
  local extra="$3"
  local preselect="$4"

  read -r -a args <<<"$extra"

  if [[ -n "$preselect" ]]; then
    local index
    index=$(echo -e "$options" | grep -nxF "$preselect" | cut -d: -f1)
    if [[ -n "$index" ]]; then
      args+=("-c" "$index")
    fi
  fi

  echo -e "$options" | omarchy-launch-walker --dmenu --width 295 --minheight 1 --maxheight 630 -p "$prompt…" "${args[@]}" 2>/dev/null
}

show_keybind_menu(){
  case $(menu "Keybinds" "  Hyprland\n  Ghostty") in
    *Hyprland*) omarchy-menu-keybindings ;;
    *Ghostty*) ./omarchy-menu-ghostty-keybindings;;
    esac
}

show_keybind_menu
